### ISSUE TITLE
'MediumMotor' object has no attribute 'connected'

### ISSUE THREAD

**Issue by heldersepu** [broccoli-97/LEGO_EV3#1]
```
2019-03-04 17:47:45,607  INFO TRACK3RWithSpinner:   15 -  <module>(): Starting TRACK3RWithSpinner
Traceback (most recent call last):
  File "/home/robot/python_code/TRACK3R/TRACK3RWithSpinner", line 16, in <module>
    tracker = TRACK3RWithSpinner()
  File "/home/robot/python_code/TRACK3R/TRACK3R.py", line 46, in __init__
    TRACK3R.__init__(self, medium_motor, left_motor, right_motor)
  File "/home/robot/python_code/TRACK3R/TRACK3R.py", line 23, in __init__
    if not self.medium_motor.connected:
AttributeError: 'MediumMotor' object has no attribute 'connected'
```

**Comment by broccoli-97** [comment]
I am very sorry about this, because I was busy preparing for the exam before, and I haven't used github for a long time, so I didn't see your issue. I apologize again.
Since I haven't followed up on this project for a long time, I am not very familiar with this code. If your problem has not been solved, I recommend you to post your problem on the python forum of EV3.
Wish all the best.
Sincerely
